### ISSUE TITLE
application become slugghy on ios after starting using uxcam

### ISSUE THREAD

**Issue by allan-simon** [uxcam/react-native-ux-cam#5]
I'm trying to use uxcam on my react native 0.6 application and while it's smooth on android, on ios activating the library makes it becomes sluggish,  and commenting the library makes it fast again

**Comment by susanuxcam** [comment]
Hey @allan-simon! Can you tell me what video quality you have selected under the Recording Settings? Aso, you can try to use react-native-screens for large stack and route improvement. What's more, we're also going to release a new SDK version in the upcoming days and this should also help with the performance!

**Comment by allan-simon** [comment]
the settings were on low,  could it be that our react application is not optimized and uxcam is affected by the fact react re-render quite often the screen ? (or uxcam is at a lower level so it is not affected by the react lifecycle ?)

**Comment by ghost** [comment]
Hi @allan-simon. re-render should not affect much. If you are facing poor navigation experience, use react-native-screens (does not support react-navigation v5 as of now for ios). For touch delay issues, we will update our SDK soon which will fix it (also refer to issue section in our react native doc). Please be patient as we're updating our SDK soon and will follow up with you in case you need more help.

**Comment by allan-simon** [comment]
ok we're using react-navigation (though not v5,  v3 I think) so that may explain, because yes switching to very low did not make the perf better

**Comment by StarryFire** [comment]
Has this issue been fixed? We are experiencing touch delays and if you rage press a button, some presses are even ignored. This only happens when uxcam is enabled! We are on a paid plan and did not expect uxcam to slow down app. Is there any deadline for this fix? If you want help reproducing the bug, please contact me.

This is happening on both android and ios for us.

**Comment by ghost** [comment]
@StarryFire this should be fixed on version 5.2.0 along with changes mentioned on our docs for ios. Issue section https://help.uxcam.com/hc/en-us/articles/115000966691-React-Native-Integration

We didn't have the issue on android but we'll get in touch with you to reproduce the issue

**Comment by StarryFire** [comment]
Hi, we are indeed on v5.2.0 and this was not fixed. 
We are working with React Native 0.62.

**Comment by raldred** [comment]
RN 0.61.5
UX Cam 5.2.0
We are too seeing the app generates lots of ANRs after visiting a screen that uses a webview.
I have debugged this to the point where the issue is "resolved" by either...

Not rendering the webview
or
Not starting uxcam

**Comment by losikov** [comment]
RN 0.63.3
UX Cam: 5.2.0
iOS only issue, sluggish right from the first screen.

To fix the issue, I have to remove import of 'react-native-ux-cam' as well. Kind of:
```
if (config.uxcamKey && Platform.OS !== 'ios') {
	const RNUxcam = require('react-native-ux-cam')
```

**Comment by qduborper** [comment]
Hi, we face a similar issue on android side only when we use it with react-native-webview
After displaying a webview, for example navigating to a new screen, the whole screen becomes sluggish with UI freezes at regular interval (every 1/2 seconds). It seems a conflict between webviews and uxcam, is there any known workaround to fix this ? Because when we remove uxcam then the freezes disappear

we are using the latest version (5.3.2)

**Comment by colin-oos** [comment]
Also facing the same issue as @raldred and @qduborper on version 5.3.4 (current latest)

I was told by their support that 5.3.4 was supposed to resolve the ANR issues after visiting a screen with a webview. It has not. We've been waiting to be able to use UXCam in our app for over half a year now.

**Comment by Anup-UXCam** [comment]
Apologies for the super late update but this should be resolved in the newer versions. Please open a new ticket if you still face these issues.
